server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

youtube:
  api:
    key: AIzaSyCWWWB5MWaGQr3ygbqYeurqyReU4RnNC5o

