server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET}

youtube:
  api:
    key: ${YOUTUBE_API_KEY}

openai:
  model: ${OPENAI_MODEL}
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}

fastapi:
  url: ${FASTAPI_URL}